name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  checks:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v12
      - run: ./bin/scalafmt --test
  docs:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v12
      - run: sbt docs/mdoc
  test:
    name: ${{ matrix.command }} ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [adopt@1.8, adopt@1.11]
        command:
          - "'++2.11.12 test'"
          # Test legacy Scala versions, where reporting API changed
          - "'++2.12.12 test'"
          - "'++2.12.13 test' scripted"
          - "'++2.13.5 test'"
          - "'++3.0.0-RC1 test'"
          - "'++3.0.0-RC2 test'"
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: ${{ matrix.java }}
      - run: sbt ${{ matrix.command }}
